
name: mirror

on: [push, pull_request]

jobs:
  mirror:
    uses: cc332030/git/.github/workflows/mirror.yml@master
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: publish
        run: ${{ secrets.GRADLE_PUBLISH_COMMAND }}
