
name: build

on:
  workflow_call:
    inputs:
      build_command:
        required: false
        type: string
        default: sh gradlew --refresh-dependencies build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: cache
        uses: actions/cache@v3
        with:
          key: gradle
          path: |
            ~/.gradle/wrapper
            ~/.gradle/jdks
            ~/.gradle/caches
      - name: build
        run: ${{ inputs.build_command }}
      - id: artifact-name
        name: artifact-name
        run: |
          echo "artifact-name=${{ github.event.repository.name }}.${{ github.ref_name }}.${{ github.run_id }}" >> $GITHUB_OUTPUT
      - name: upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.artifact-name.outputs.artifact-name }}
          path: |
            build
