
name:  deploy-image-dockerfile

on:
  workflow_call:
    inputs:
      distribution:
        required: false
        type: string
        default: temurin
      java-version:
        required: false
        type: string
        default: 17
      build-before-image:
        required: false
        type: string
        default: true
      registry:
        required: false
        type: string
        default: docker.io
      artifact-enable:
        required: false
        type: string
        default: true
      artifact-path:
        required: false
        type: string
        default: |
          build
    secrets:
      SSH_PRIVATE_KEY:
        required: false
      HOST:
        required: false
      PORT:
        required: false
      IMAGE_NAME:
        required: false
      REGISTRY_USERNAME:
        required: true
      REGISTRY_PASSWORD:
        required: true

jobs:
  deploy-image-dockerfile:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v4
      -
        name: cache
        uses: actions/cache@v4
        if: ${{ inputs.build-before-image == 'true' }}
        with:
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle.properties','**/build.gradle*','**/settings.gradle*','**/gradle-wrapper.properties') }}
          path: |
            ~/.gradle/wrapper
            ~/.gradle/jdks
            ~/.gradle/caches
      -
        name: setup-java
        uses: actions/setup-java@v4
        if: ${{ inputs.build-before-image == 'true' && inputs.java-version != '' }}
        with:
          distribution: ${{ inputs.distribution }}
          java-version: ${{ inputs.java-version }}
      -
        name: build
        if: ${{ inputs.build-before-image == 'true' }}
        run: sh gradlew --refresh-dependencies build
      -
        name: image-name
        if: ${{ env.IMAGE_NAME != '' }}
        env:
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
        run: |
          echo "IMAGE_NAME=${{ inputs.registry }}/${{ env.IMAGE_NAME }}" >> $GITHUB_ENV
      -
        name: image-name-default
        if: ${{ env.IMAGE_NAME == '' }}
        env:
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
        run: |
          echo "IMAGE_NAME=${{ inputs.registry }}/${{ secrets.REGISTRY_USERNAME }}/${{ github.event.repository.name }}" >> $GITHUB_ENV

      -
        name: buildx
        uses: docker/setup-buildx-action@v3
      -
        name: login
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      -
        name: dockerfile
        run: if [ ! -f dockerfile ]; then wget -q --show-progress -O dockerfile https://github.com/cc332030/gradle/raw/master/docker/dockerfile; fi
      -
        name: build-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.ref_name }}
            ${{ env.IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache,mode=max
      -
        name: init-ssh-pre
        if: ${{ env.SSH_PRIVATE_KEY != '' }}
        run: curl -sL https://github.com/cc332030/linux/raw/master/script/init-ssh/init-ssh-pre.sh | sudo sh
      -
        id: init-ssh
        name: init-ssh
        if: ${{ env.SSH_PRIVATE_KEY != '' }}
        run: curl -sL https://github.com/cc332030/linux/raw/master/script/init-ssh/init-ssh.sh | sh
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      -
        name: start
        if: ${{ steps.init-ssh.outcome == 'success' }}
        run: ssh -o LogLevel=ERROR -p ${{ secrets.PORT }} root@${{ secrets.HOST }} \
          "cd /home/program/${{ github.event.repository.name }} && dcomposeinit -d"
      -
        id: artifact-name
        name: artifact-name
        if: ${{ inputs.artifact-enable == 'true' }}
        run: |
          echo "artifact-name=${{ github.event.repository.name }}.${{ github.ref_name }}.${{ github.run_id }}" >> $GITHUB_OUTPUT
      -
        name: upload-artifact
        uses: actions/upload-artifact@v4
        if: ${{ inputs.artifact-enable == 'true' }}
        with:
          name: ${{ steps.artifact-name.outputs.artifact-name }}
          path: ${{ inputs.artifact-path }}
          retention-days: 1
      -
        name: init-ssh-clean
        if: ${{ always() }}
        run: curl -sL https://github.com/cc332030/linux/raw/master/script/init-ssh/init-ssh-clean.sh | sh
