
name: deploy

on:
  workflow_call:
    inputs:
      distribution:
        required: false
        type: string
        default: temurin
      java-version:
        required: false
        type: string
        default: 21
      origin-path:
        required: true
        type: string
      remote-path:
        required: true
        type: string
      prepare-command:
        required: false
        type: string
      action-command:
        required: false
        type: string
      artifact-path:
        required: false
        type: string
        default: |
          build
      env-file:
        required: false
        type: string
        default: .env
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      HOST:
        required: true
      PORT:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      -
        name: set-java-version
        if: ${{ inputs.java-version != '' }}
        run: |
          echo "JAVA_VERSION=${{ inputs.java-version }}" >> $GITHUB_ENV
      -
        name: import-env
        if: ${{ hashFiles(inputs.env-file) != '' }}
        run: cat ${{inputs.env-file}} >> $GITHUB_ENV
      - name: cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-gradle-${{ hashFiles('.env','**/gradle.properties', '**/build.gradle*','**/settings.gradle*','**/gradle-wrapper.properties') }}
          path: |
            ~/.gradle/wrapper
            ~/.gradle/jdks
            ~/.gradle/caches
      - name: setup-java
        uses: actions/setup-java@v4
        if: ${{ env.JAVA_VERSION != '' }}
        with:
          distribution: ${{ inputs.distribution }}
          java-version: ${{ env.JAVA_VERSION }}
      - name: build
        run: sh gradlew build -U
      - id: artifact-name
        name: artifact-name
        run: |
          echo "artifact-name=${{ github.event.repository.name }}.${{ github.ref_name }}.${{ github.run_id }}" >> $GITHUB_OUTPUT
      - name: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.artifact-name.outputs.artifact-name }}
          path: ${{ inputs.artifact-path }}
          retention-days: 7
      - name: init-ssh-pre
        run: curl -sL https://github.com/cc332030/linux/raw/master/script/init-ssh/init-ssh-pre.sh | sudo sh
      - name: init-ssh
        run: curl -sL https://github.com/cc332030/linux/raw/master/script/init-ssh/init-ssh.sh | sh
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: deploy
        run: curl -sL https://github.com/cc332030/linux/raw/master/script/deploy/deploy.sh | sh
        timeout-minutes: 2
        env:
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
          ORIGIN_PATH: ${{ inputs.origin-path }}
          REMOTE_PATH: ${{ inputs.remote-path }}
          PREPARE_COMMAND: ${{ inputs.prepare-command }}
          ACTION_COMMAND: ${{ inputs.action-command }}
      - name: init-ssh-clean
        if: ${{ always() }}
        run: curl -sL https://github.com/cc332030/linux/raw/master/script/init-ssh/init-ssh-clean.sh | sh
