
name: deploy

on:
  workflow_call:
    inputs:
      origin-path:
        required: true
        type: string
      remote-path:
        required: true
        type: string
      prepare-command:
        required: false
        type: string
      action-command:
        required: false
        type: string
      multi-module:
        required: false
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      HOST:
        required: true
      PORT:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: cache
        uses: actions/cache@v3
        with:
          key: gradle
          path: |
            ~/.gradle/wrapper
            ~/.gradle/jdks
            ~/.gradle/caches
      - name: build
        run: sh gradlew --refresh-dependencies build
      - id: artifact-name
        name: artifact-name
        run: |
          echo "artifact-name=${{ github.event.repository.name }}.${{ github.ref_name }}.${{ github.run_id }}" >> $GITHUB_OUTPUT
      - name: upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.artifact-name.outputs.artifact-name }}
          path: |
            build
      - name: init-ssh-pre
        run: curl -sL https://github.com/cc332030/linux/raw/master/script/init-ssh/init-ssh-pre.sh | sudo sh
      - name: init-ssh
        run: curl -sL https://github.com/cc332030/linux/raw/master/script/init-ssh/init-ssh.sh | sh
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: deploy
        run: curl -sL https://github.com/cc332030/linux/raw/master/script/deploy/deploy.sh | sh
        timeout-minutes: 2
        env:
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
          ORIGIN_PATH: ${{ inputs.origin-path }}
          REMOTE_PATH: ${{ inputs.remote-path }}
          PREPARE_COMMAND: ${{ inputs.prepare-command }}
          ACTION_COMMAND: ${{ inputs.action-command }}
          MULTI_MODULE: ${{ inputs.multi-module }}
      - name: init-ssh-clean
        if: ${{ always() }}
        run: curl -sL https://github.com/cc332030/linux/raw/master/script/init-ssh/init-ssh-clean.sh | sh
