
name:  deploy-image-dockerfile

on:
  workflow_call:
    inputs:
      build-before-image:
        required: false
        type: string
        default: true
      dockerfile:
        required: false
        type: string
        default: dockerfile
      distribution:
        required: false
        type: string
        default: temurin
      java-version:
        required: false
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      HOST:
        required: true
      PORT:
        required: true
      DOCKER_TOKEN:
        required: true

jobs:
  deploy-image-dockerfile:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v3
      -
        name: cache
        uses: actions/cache@v3
        if: ${{ inputs.build-before-image }}
        with:
          key: gradle
          path: |
            ~/.gradle/wrapper
            ~/.gradle/jdks
            ~/.gradle/caches
      -
        name: setup-java
        uses: actions/setup-java@v3
        if: ${{ inputs.build-before-image }}
        with:
          distribution: ${{ inputs.distribution }}
          java-version: ${{ inputs.java-version }}
      -
        name: build
        if: ${{ inputs.build-before-image }}
        run: sh gradlew --refresh-dependencies build
      -
        name: login
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: build-push
        uses: docker/build-push-action@v4
        with:
          file: ${{ inputs.dockerfile }}
          push: true
          tags: |
            ${{ github.actor }}/${{ github.event.repository.name }}:${{ github.ref_name }}
            ${{ github.actor }}/${{ github.event.repository.name }}:latest
      -
        name: init-ssh-pre
        run: curl -sL https://github.com/cc332030/linux/raw/master/script/init-ssh/init-ssh-pre.sh | sudo sh
      -
        name: init-ssh
        run: curl -sL https://github.com/cc332030/linux/raw/master/script/init-ssh/init-ssh.sh | sh
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      -
        name: start
        run: ssh -o LogLevel=ERROR -p ${{ secrets.PORT }} root@${{ secrets.HOST }} \
          "cd /home/program/${{ github.event.repository.name }} && dcomposeinit -d"
      -
        name: init-ssh-clean
        if: ${{ always() }}
        run: curl -sL https://github.com/cc332030/linux/raw/master/script/init-ssh/init-ssh-clean.sh | sh
