
name:  deploy-image-dockerfile

on:
  workflow_call:
    inputs:
      distribution:
        required: false
        type: string
        default: temurin
      java-version:
        required: false
        type: string
        default: 17
      build-before-image:
        required: false
        type: string
        default: true
      registry:
        required: false
        type: string
        default: docker.io
      dockerfile:
        required: false
        type: string
        default: dockerfile
      artifact-path:
        required: false
        type: string
        default: |
          build
    secrets:
      SSH_PRIVATE_KEY:
        required: false
      HOST:
        required: true
      PORT:
        required: true
      REGISTRY_USERNAME:
        required: true
      REGISTRY_PASSWORD:
        required: true

jobs:
  deploy-image-dockerfile:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v3
      -
        name: cache
        uses: actions/cache@v3
        if: ${{ inputs.build-before-image == 'true' }}
        with:
          key: gradle
          path: |
            ~/.gradle/wrapper
            ~/.gradle/jdks
            ~/.gradle/caches
      -
        name: setup-java
        uses: actions/setup-java@v3
        if: ${{ inputs.build-before-image == 'true' && inputs.java-version != '' }}
        with:
          distribution: ${{ inputs.distribution }}
          java-version: ${{ inputs.java-version }}
      -
        name: build
        if: ${{ inputs.build-before-image == 'true' }}
        run: sh gradlew --refresh-dependencies build
      -
        id: image-name
        name: image-name
        run: |
          echo "image-name=${{ inputs.registry }}/${{ github.actor }}/${{ github.event.repository.name }}" >> $GITHUB_OUTPUT
      -
        name: buildx
        uses: docker/setup-buildx-action@v2
      -
        name: login
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      -
        name: build-push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          push: true
          tags: |
            ${{ steps.image-name.outputs.image-name }}:${{ github.ref_name }}
            ${{ steps.image-name.outputs.image-name }}:latest
          cache-from: type=registry,ref=${{ steps.image-name.outputs.image-name }}:buildcache
          cache-to: type=registry,ref=${{ steps.image-name.outputs.image-name }}:buildcache,mode=max
      -
        name: init-ssh-pre
        run: curl -sL https://github.com/cc332030/linux/raw/master/script/init-ssh/init-ssh-pre.sh | sudo sh
      -
        id: init-ssh
        name: init-ssh
        if: ${{ env.SSH_PRIVATE_KEY != '' }}
        run: curl -sL https://github.com/cc332030/linux/raw/master/script/init-ssh/init-ssh.sh | sh
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      -
        name: start
        if: ${{ steps.init-ssh.outcome == 'success' }}
        run: ssh -o LogLevel=ERROR -p ${{ secrets.PORT }} root@${{ secrets.HOST }} \
          "cd /home/program/${{ github.event.repository.name }} && dcomposeinit -d"
      -
        id: artifact-name
        name: artifact-name
        run: |
          echo "artifact-name=${{ github.event.repository.name }}.${{ github.ref_name }}.${{ github.run_id }}" >> $GITHUB_OUTPUT
      -
        name: upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.artifact-name.outputs.artifact-name }}
          path: ${{ inputs.artifact-path }}
          retention-days: 7
      -
        name: init-ssh-clean
        if: ${{ always() }}
        run: curl -sL https://github.com/cc332030/linux/raw/master/script/init-ssh/init-ssh-clean.sh | sh
