
name: gradle

on:
  workflow_call:
    secrets:
      GPG_PRIVATE_KEY:
        required: false
      GPG_PASSWORD:
        required: false
      GPG_SIGN_KEY:
        required: false
      OSSRH_USERNAME:
        required: false
      OSSRH_PASSWORD:
        required: false
    inputs:
      command:
        required: true
        type: string

jobs:
  gradle:
    name: gradle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cc332030/gradle-action@main
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
          GPG_SIGN_KEY: ${{ secrets.GPG_SIGN_KEY }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        with:
          command: ${{ inputs.command }}
