
name: publish

on:
  workflow_call:
    inputs:
      distribution:
        required: false
        type: string
        default: temurin
      java-version:
        required: false
        type: string
      artifact-path:
        required: false
        type: string
        default: |
          build
    secrets:
      GPG_PRIVATE_KEY:
        required: true
      GPG_PASSWORD:
        required: true
      GPG_SIGN_KEY:
        required: true
      OSSRH_USERNAME:
        required: true
      OSSRH_PASSWORD:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: init-gpg
        run: curl -sL https://github.com/cc332030/gnupg/raw/main/script/init-gpg/init-gpg.sh | sh
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
      - name: init-gradle
        run: curl -sL https://github.com/cc332030/gradle/raw/master/script/init-gradle/init-gradle.sh | sh
        env:
          GPG_SIGN_KEY: ${{ secrets.GPG_SIGN_KEY }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      - name: cache
        uses: actions/cache@v3
        with:
          key: gradle
          path: |
            ~/.gradle/wrapper
            ~/.gradle/jdks
            ~/.gradle/caches
      - name: setup-java
        uses: actions/setup-java@v3
        if: ${{ inputs.java-version != '' }}
        with:
          distribution: ${{ inputs.distribution }}
          java-version: ${{ inputs.java-version }}
      - name: publish
        run: sh gradlew --refresh-dependencies publish
      - id: artifact-name
        name: artifact-name
        run: |
          echo "artifact-name=${{ github.event.repository.name }}.${{ github.ref_name }}.${{ github.run_id }}" >> $GITHUB_OUTPUT
      - name: upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.artifact-name.outputs.artifact-name }}
          path: ${{ inputs.artifact-path }}
          retention-days: 3
      - name: init-gpg-clean
        if: ${{ always() }}
        run: curl -sL https://github.com/cc332030/gnupg/raw/main/script/init-gpg/init-gpg-clean.sh | sh
      - name: init-gradle-clean
        if: ${{ always() }}
        run: curl -sL https://github.com/cc332030/gradle/raw/master/script/init-gradle/init-gradle-clean.sh | sh
